exclude: '^$'
fail_fast: false
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      # - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['-r', '--in-place',
               '--remove-all-unused-imports',
               '--ignore-init-module-imports',
               '--remove-unused-variables',
               '--remove-duplicate-keys'
              ]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args: ['--application-directories=src']

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--profile=black"

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        args:
          - "--line-length=120"